repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.3.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: requirements-txt-fixer
-   repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
    -   id: black
        language_version: python3
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.4
    hooks:
    -   id: flake8
        args: ["--max-line-length=88", "--extend-ignore=E203"]
-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.6.4
    hooks:
    -   id: isort
-   repo: https://gitlab.com/jvenom/elixir-pre-commit-hooks
    rev: v1.0.0
    hooks:
    -   id: mix-format
-   repo: https://github.com/pre-commit/mirrors-eslint
    rev: v7.15.0
    hooks:
    -   id: eslint
        args: ["--fix"]
        additional_dependencies:
            - "@typescript-eslint/parser@4.9.0"
            - "@typescript-eslint/eslint-plugin@4.9.0"
            - eslint-config-prettier@7.0.0
            - eslint-plugin-prettier@3.2.0
            - prettier@2.2.1
        files: \.ts$
        types: [file]
-   repo: https://github.com/doublify/pre-commit-rust
    rev: v1.0
    hooks:
    -   id: fmt
    -   id: cargo-check
    -   id: clippy
